"""
页面类型定义 — 适配紧凑视口
组件数量范围大幅缩减, 布局偏好更新为新布局名
"""
import random

PAGE_TYPES = {
    "dashboard": {
        "label": "数据仪表盘",
        "required": ["navbar", "stats"],
        "optional": ["chart_placeholder", "table", "progress_group", "alert", "breadcrumb", "card_grid"],
        "component_range": (3, 6),
        "layout_prefer": ["dashboard_stack", "sidebar_left", "stack"],
    },
    "dashboard_brief": {
        "label": "简版数据面板",
        "required": ["navbar", "stats"],
        "optional": ["chart_placeholder", "progress_group", "alert", "breadcrumb", "divider"],
        "component_range": (3, 5),
        "layout_prefer": ["dashboard_stack", "stack"],
    },
    "analytics_story": {
        "label": "分析故事面板",
        "required": ["navbar", "timeline"],
        "optional": ["stats", "chart_placeholder", "table", "alert", "filter_bar"],
        "component_range": (3, 6),
        "layout_prefer": ["dashboard_stack", "stack"],
    },
    "ecommerce_listing": {
        "label": "电商商品列表",
        "required": ["navbar", "card_grid"],
        "optional": ["breadcrumb", "filter_bar", "pagination", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack", "stack_narrow"],
    },
    "ecommerce_category": {
        "label": "电商分类页",
        "required": ["navbar", "filter_bar", "card_grid"],
        "optional": ["breadcrumb", "pagination", "footer", "badge_group"],
        "component_range": (4, 6),
        "layout_prefer": ["stack_narrow", "sidebar_left", "stack"],
    },
    "ecommerce_detail": {
        "label": "商品详情页",
        "required": ["navbar", "product_detail"],
        "optional": ["breadcrumb", "badge_group", "review_list", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "ecommerce_compare": {
        "label": "商品对比页",
        "required": ["navbar", "table", "related_cards"],
        "optional": ["breadcrumb", "badge_group", "filter_bar", "footer"],
        "component_range": (4, 6),
        "layout_prefer": ["sidebar_left", "stack_narrow", "stack"],
    },
    "ecommerce_cart": {
        "label": "购物车页",
        "required": ["navbar", "card_grid"],
        "optional": ["breadcrumb", "pagination", "footer", "alert", "filter_bar"],
        "component_range": (3, 5),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "ecommerce_checkout": {
        "label": "结算页",
        "required": ["navbar", "form_group"],
        "optional": ["breadcrumb", "toggle_group", "tabs", "alert", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack_narrow", "sidebar_left", "stack"],
    },
    "ecommerce_account_orders": {
        "label": "订单中心",
        "required": ["navbar", "file_list"],
        "optional": ["breadcrumb", "pagination", "alert", "timeline", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack", "sidebar_left", "stack_narrow"],
    },
    "blog_article": {
        "label": "博客文章",
        "required": ["navbar", "article_body"],
        "optional": ["breadcrumb", "tag_group", "comment_list", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "blog_review": {
        "label": "内容评论页",
        "required": ["navbar", "review_list"],
        "optional": ["breadcrumb", "comment_list", "tabs", "footer"],
        "component_range": (2, 4),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "help_center_article": {
        "label": "帮助中心文章",
        "required": ["navbar", "article_body", "sidebar_toc"],
        "optional": ["breadcrumb", "code_block", "tabs", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["sidebar_left", "stack_narrow"],
    },
    "settings_page": {
        "label": "设置页面",
        "required": ["navbar", "form_group"],
        "optional": ["breadcrumb", "tabs", "toggle_group", "alert"],
        "component_range": (3, 5),
        "layout_prefer": ["stack_narrow", "sidebar_left", "stack"],
    },
    "user_profile_edit": {
        "label": "个人资料编辑",
        "required": ["navbar", "profile_header", "form_group"],
        "optional": ["breadcrumb", "tabs", "badge_group", "footer"],
        "component_range": (4, 6),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "user_security_settings": {
        "label": "安全设置页",
        "required": ["navbar", "toggle_group"],
        "optional": ["breadcrumb", "alert", "form_group", "tabs", "footer"],
        "component_range": (2, 4),
        "layout_prefer": ["stack_narrow", "sidebar_left", "stack"],
    },
    "support_center": {
        "label": "客服中心",
        "required": ["navbar", "file_list"],
        "optional": ["breadcrumb", "form_group", "faq_accordion", "alert", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["sidebar_left", "stack", "stack_narrow"],
    },
    "user_profile": {
        "label": "用户资料",
        "required": ["navbar", "profile_header"],
        "optional": ["stats", "tabs", "badge_group", "card_grid", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack", "stack_narrow"],
    },
    "portfolio_gallery": {
        "label": "作品集画廊",
        "required": ["navbar", "card_grid"],
        "optional": ["breadcrumb", "profile_header", "related_cards", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack", "stack_narrow"],
    },
    "analytics": {
        "label": "数据分析",
        "required": ["navbar", "stats"],
        "optional": ["chart_placeholder", "filter_bar", "table", "progress_group"],
        "component_range": (3, 6),
        "layout_prefer": ["dashboard_stack", "stack"],
    },
    "analytics_table_view": {
        "label": "表格分析视图",
        "required": ["navbar", "table"],
        "optional": ["stats", "filter_bar", "pagination", "chart_placeholder", "footer"],
        "component_range": (3, 6),
        "layout_prefer": ["sidebar_left", "dashboard_stack", "stack"],
    },
    "landing_page": {
        "label": "落地页",
        "required": ["navbar", "hero_banner"],
        "optional": ["feature_grid", "stats", "testimonial_cards", "cta_section", "footer"],
        "component_range": (3, 6),
        "layout_prefer": ["hero_stack", "stack"],
    },
    "landing_product": {
        "label": "产品落地页",
        "required": ["navbar", "hero_banner", "feature_grid"],
        "optional": ["cta_section", "stats", "testimonial_cards", "footer"],
        "component_range": (4, 6),
        "layout_prefer": ["hero_stack", "stack"],
    },
    "notification_center": {
        "label": "通知中心",
        "required": ["navbar", "comment_list"],
        "optional": ["filter_bar", "pagination", "alert", "footer"],
        "component_range": (2, 4),
        "layout_prefer": ["stack", "stack_narrow"],
    },
    "rating_center": {
        "label": "评分与反馈",
        "required": ["navbar", "rating_display"],
        "optional": ["stats", "alert", "tabs", "footer"],
        "component_range": (2, 4),
        "layout_prefer": ["center_card", "stack"],
    },
    "admin_panel": {
        "label": "管理后台",
        "required": ["navbar", "table"],
        "optional": ["stats", "breadcrumb", "alert", "pagination", "filter_bar"],
        "component_range": (3, 6),
        "layout_prefer": ["sidebar_left", "dashboard_stack", "stack"],
    },
    "admin_audit_trail": {
        "label": "审计日志",
        "required": ["navbar", "timeline"],
        "optional": ["stats", "filter_bar", "table", "alert", "footer"],
        "component_range": (3, 6),
        "layout_prefer": ["sidebar_left", "dashboard_stack", "stack"],
    },
    "chat_interface": {
        "label": "聊天界面",
        "required": ["navbar", "chat_bubbles", "input_area"],
        "optional": [],
        "component_range": (3, 3),
        "layout_prefer": ["chat_layout"],
    },
    "file_manager": {
        "label": "文件管理器",
        "required": ["navbar", "file_list"],
        "optional": ["breadcrumb", "toolbar", "pagination"],
        "component_range": (3, 5),
        "layout_prefer": ["sidebar_left", "stack"],
    },
    "help_code_reference": {
        "label": "代码参考页",
        "required": ["navbar", "code_block"],
        "optional": ["breadcrumb", "tabs", "footer", "alert"],
        "component_range": (2, 4),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "calendar_page": {
        "label": "日历页",
        "required": ["navbar", "calendar_grid"],
        "optional": ["breadcrumb", "event_list"],
        "component_range": (3, 4),
        "layout_prefer": ["stack", "stack_narrow"],
    },
    "calendar_agenda": {
        "label": "日程与议程",
        "required": ["navbar", "calendar_grid", "date_range_picker"],
        "optional": ["breadcrumb", "event_list", "timeline", "footer"],
        "component_range": (4, 5),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "kanban_board": {
        "label": "看板",
        "required": ["navbar", "kanban_columns"],
        "optional": ["breadcrumb", "filter_bar", "avatar_group"],
        "component_range": (2, 4),
        "layout_prefer": ["stack"],
    },
    "task_event_board": {
        "label": "任务事件看板",
        "required": ["navbar", "kanban_columns"],
        "optional": ["filter_bar", "event_list", "avatar_group", "timeline", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack", "stack_narrow"],
    },
    "email_client": {
        "label": "邮件客户端",
        "required": ["navbar", "email_list"],
        "optional": ["toolbar", "pagination"],
        "component_range": (2, 4),
        "layout_prefer": ["stack", "sidebar_left"],
    },
    "email_detail_view": {
        "label": "邮件详情",
        "required": ["navbar", "email_detail"],
        "optional": ["breadcrumb", "toolbar", "email_list", "pagination", "footer"],
        "component_range": (2, 4),
        "layout_prefer": ["stack_narrow", "sidebar_left", "stack"],
    },
    "social_feed": {
        "label": "社交动态",
        "required": ["navbar", "feed_cards"],
        "optional": ["story_bar", "suggestion_list", "footer"],
        "component_range": (2, 4),
        "layout_prefer": ["stack", "stack_narrow"],
    },
    "community_forum": {
        "label": "社区论坛",
        "required": ["navbar", "feed_cards", "comment_list"],
        "optional": ["suggestion_list", "story_bar", "footer", "tabs", "filter_bar"],
        "component_range": (3, 5),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "documentation": {
        "label": "文档页",
        "required": ["navbar", "article_body"],
        "optional": ["breadcrumb", "sidebar_toc", "tabs", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["stack_narrow", "sidebar_left"],
    },
    "faq_center": {
        "label": "常见问题",
        "required": ["navbar", "faq_accordion"],
        "optional": ["breadcrumb", "alert", "rating_display", "footer"],
        "component_range": (2, 4),
        "layout_prefer": ["stack_narrow", "stack"],
    },
    "pricing_variants": {
        "label": "定价变体页",
        "required": ["navbar", "pricing_table", "hero_banner"],
        "optional": ["faq_accordion", "cta_section", "footer", "testimonial_cards"],
        "component_range": (4, 6),
        "layout_prefer": ["hero_stack", "stack"],
    },
    "pricing_page": {
        "label": "定价页",
        "required": ["navbar", "pricing_table"],
        "optional": ["hero_banner", "faq_accordion", "cta_section", "footer"],
        "component_range": (3, 5),
        "layout_prefer": ["hero_stack", "stack"],
    },
    "auth_page": {
        "label": "登录/注册",
        "required": ["auth_form"],
        "optional": ["alert", "hero_side"],
        "component_range": (1, 2),
        "layout_prefer": ["center_card", ],
    },
    "error_page": {
        "label": "错误页",
        "required": ["error_display"],
        "optional": ["navbar", "footer"],
        "component_range": (1, 3),
        "layout_prefer": ["center_card", "stack"],
    },
    "project_management": {
        "label": "项目管理",
        "required": ["navbar", "stats"],
        "optional": ["table", "breadcrumb", "progress_group", "timeline", "alert"],
        "component_range": (3, 6),
        "layout_prefer": ["dashboard_stack", "sidebar_left", "stack"],
    },
}


def pick_page_type(name=None):
    if name and name in PAGE_TYPES:
        return name, PAGE_TYPES[name]
    key = random.choice(list(PAGE_TYPES.keys()))
    return key, PAGE_TYPES[key]